# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfarce.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1171, 531)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(560, 130, 411, 151))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.search = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.search.setObjectName("search")
        self.horizontalLayout.addWidget(self.search)
        self.fire = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.fire.setObjectName("fire")
        self.horizontalLayout.addWidget(self.fire)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(50, 320, 160, 151))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.amos = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.amos.setObjectName("amos")
        self.verticalLayout.addWidget(self.amos)
        self.distance = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.distance.setObjectName("distance")
        self.verticalLayout.addWidget(self.distance)
        self.elevaation = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.elevaation.setObjectName("elevaation")
        self.verticalLayout.addWidget(self.elevaation)
        self.orientation = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.orientation.setObjectName("orientation")
        self.verticalLayout.addWidget(self.orientation)
        self.cameraLabel = QtWidgets.QGraphicsView(Dialog)
        self.cameraLabel.setGeometry(QtCore.QRect(600, 300, 256, 192))
        self.cameraLabel.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.cameraLabel.setAcceptDrops(True)
        self.cameraLabel.setObjectName("cameraLabel")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(572, 20, 391, 89))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.status = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.status.setObjectName("status")
        self.horizontalLayout_2.addWidget(self.status)
        self.searching = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.searching.setObjectName("searching")
        self.horizontalLayout_2.addWidget(self.searching)
        self.target = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.target.setObjectName("target")
        self.horizontalLayout_2.addWidget(self.target)
        self.shooting = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.shooting.setObjectName("shooting")
        self.horizontalLayout_2.addWidget(self.shooting)
        self.Switch = QtWidgets.QLabel(Dialog)
        self.Switch.setGeometry(QtCore.QRect(80, 65, 55, 41))
        self.Switch.setObjectName("Switch")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.search.setText(_translate("Dialog", "Search"))
        self.fire.setText(_translate("Dialog", "Fire"))
        self.amos.setText(_translate("Dialog", "Amos"))
        self.distance.setText(_translate("Dialog", "Distance"))
        self.elevaation.setText(_translate("Dialog", "Elevation "))
        self.orientation.setText(_translate("Dialog", "Orientation"))
        self.status.setText(_translate("Dialog", "Status"))
        self.searching.setText(_translate("Dialog", "Searching"))
        self.target.setText(_translate("Dialog", "Target"))
        self.shooting.setText(_translate("Dialog", "Shooting"))
        self.Switch.setText(_translate("Dialog", "Off/On"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
